### ISSUE TITLE
The project seems to require yarn but it's not installed.

### ISSUE THREAD

**Issue by 0xOzgur** [LuaxY/etb-voting-app#3]
Hi mate,
Thank you for your project, I really want to work on it to learn deeper but when I push yarn serve, I have error and stucked as a newbie.

I will apprecieate your help.

99% done plugins ERROR  Error: The project seems to require yarn but it's not installed.
Error: The project seems to require yarn but it's not installed.
    at checkYarn (D:\GitHub\etb-voting-app\node_modules\@vue\cli-shared-utils\lib\env.js:46:43)
    at exports.hasProjectYarn (D:\GitHub\etb-voting-app\node_modules\@vue\cli-shared-utils\lib\env.js:42:10)
    at D:\GitHub\etb-voting-app\node_modules\@vue\cli-service\lib\commands\serve.js:295:34
    at Hook.eval [as callAsync] (eval at create (D:\GitHub\etb-voting-app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:62:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\GitHub\etb-voting-app\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (D:\GitHub\etb-voting-app\node_modules\webpack\lib\Watching.js:261:28)
    at D:\GitHub\etb-voting-app\node_modules\webpack\lib\Watching.js:183:21
    at Compiler.emitRecords (D:\GitHub\etb-voting-app\node_modules\webpack\lib\Compiler.js:874:39)
    at D:\GitHub\etb-voting-app\node_modules\webpack\lib\Watching.js:161:22
    at D:\GitHub\etb-voting-app\node_modules\webpack\lib\Compiler.js:856:14
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by LuaxY** [comment]
Hello
Please install yarn via npm
https://yarnpkg.com/getting-started/install

And run `yarn install`

**Comment by LuaxY** [comment]
Also, since you have forked an old repo, please apply this two fixes on yours 
https://github.com/EatTheBlocks/voting/commit/a5e86b91da7475495cfb69135d26286c1af18e48
https://github.com/EatTheBlocks/voting/commit/289a7303932f1c5c7bea728a8db702cd5c2955c6
